name: handasaimschedule
description: "אפליקציה להצגת המערכת היומית בתיכון הנדסאים"
publish_to: 'none'
version: 1.2.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  google_fonts: ^6.3.1
  shared_preferences: ^2.5.3
  dynamic_color: ^1.8.1
  flutter_animate: ^4.5.2
  archive: ^4.0.7
  html: ^0.15.6
  flutter_riverpod: ^3.0.3
  wave_progress_indicator: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true